package com.renly.bean;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_department.id
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_department.dept_name
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_department.id
     *
     * @return the value of mybatis_department.id
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_department.id
     *
     * @param id the value for mybatis_department.id
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_department.dept_name
     *
     * @return the value of mybatis_department.dept_name
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_department.dept_name
     *
     * @param deptName the value for mybatis_department.dept_name
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}