package com.renly.bean;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_employee.ID
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_employee.LAST_NAME
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_employee.EMAIL
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mybatis_employee.DEPT_ID
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_employee.ID
     *
     * @return the value of mybatis_employee.ID
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_employee.ID
     *
     * @param id the value for mybatis_employee.ID
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_employee.LAST_NAME
     *
     * @return the value of mybatis_employee.LAST_NAME
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_employee.LAST_NAME
     *
     * @param lastName the value for mybatis_employee.LAST_NAME
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_employee.EMAIL
     *
     * @return the value of mybatis_employee.EMAIL
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_employee.EMAIL
     *
     * @param email the value for mybatis_employee.EMAIL
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mybatis_employee.DEPT_ID
     *
     * @return the value of mybatis_employee.DEPT_ID
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mybatis_employee.DEPT_ID
     *
     * @param deptId the value for mybatis_employee.DEPT_ID
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}