package com.renly.dao;

import com.renly.bean.Department;
import com.renly.bean.DepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_department
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    int countByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_department
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    int deleteByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_department
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_department
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    int insert(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_department
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    int insertSelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_department
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    List<Department> selectByExample(DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_department
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    Department selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_department
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_department
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    int updateByExample(@Param("record") Department record, @Param("example") DepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_department
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    int updateByPrimaryKeySelective(Department record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mybatis_department
     *
     * @mbggenerated Sun Jul 14 15:19:01 CST 2019
     */
    int updateByPrimaryKey(Department record);
}